name: Generate Artifacts

on:
  push:
    branches:
      - main
    paths:
      - 'TodoList.andes'
      - '.github/workflows/generate-artifacts.yml'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      - name: Setup Github
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull --rebase origin main
      - name: Run Andes CLI
        run: npx andes-cli generate ./TodoList.andes
      - name: Commit and push Andes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "chore: generate artifacts [skip ci]"
          git remote set-url origin https://x-access-token:${{ secrets.REPOSITORY_TOKEN }}@github.com/${{ github.repository }}
          git push

      - name: Run Spark CLI
        run: npx spark-cli generate ./artifacts/ToDoList.spark
      - name: Commit and push Spark
        run: |
          git add .
          git diff --cached --quiet || git commit -m "chore: generate artifacts [skip ci]"
          git remote set-url origin https://x-access-token:${{ secrets.REPOSITORY_TOKEN }}@github.com/${{ github.repository }}
          git push

      # - name: Run Made CLI
      #   run: npx made-cli generate ./artifacts/TodoList.made
      # - name: Commit and push Made
      #   run: |
      #     git add .
      #     git diff --cached --quiet || git commit -m "chore: generate artifacts [skip ci]"
      #     git remote set-url origin https://x-access-token:${{ secrets.REPOSITORY_TOKEN }}@github.com/${{ github.repository }}
      #     git push

